---
title: ""
date: 2021-06-07T14:14:44+08:00
draft: true
---

** life
In 7 June 2021, I dream about suicide. It's may be rediculous to talk this topic in one's twenty nearby. However, I would like to write something to record what I thought for a long time. That life is tough is known to everyone, but stil too boring  for me. Most People--what we called general people, are struggling to fight porverty, to gain a little reputation--or just to say alive. If you have a friend--no matter in interest's aspect or mental aspect, you will get easier, and that's could almost the essential reason why they always intend to look for partners, companion, and also organazations. They compete with others and hence gain something. They alias this process "live". Do we really need competiton? Yes, Darwin's theorem tells us Competition makes evolution. However, Do competiton will satisfy one's appeal--especially those root in our heart? My answer is No. Loneness is the everlasting and unique choice of men. I have realized that in my ealy age. You have to face loneness because no one can really understand you. As I said before, life is boring, but not the always case. I usually love finding and doing something interesting things to amuse myself. Besides, I also entertain other people and see their reaction. However, seldom people will understand this. I do many things just for fun. In the beginning, I found it will be a little difficult to do those things. But I'm more easier with that gradually. In fact, you can do many things in a more funny way and you can get pleasure. Well, The very interesting point is that you can do things in both efficient and enjoyable way in most cases--like Richard Feynman, who is both totally a genius and also comedy actor.
